In [51]:
# Cell 1: NumPy 임포트 및 배열 기초
import numpy as np

a = np.array([1, 4, 5, 7])
print("1차원 배열 a:", a)
print("첫 번째 요소 a[0]:", a[0])

1차원 배열 a: [1 4 5 7]
첫 번째 요소 a[0]: 1


In [52]:
# Cell 2: 특정 값으로 채워진 배열 생성
print("zeros(2):", np.zeros(2))
print("ones(2):", np.ones(2))
print("empty(2):", np.empty(2))   # 메모리 상태에 따라 값이 달라질 수 있음
print("arange(4):", np.arange(4))
print("arange(2, 9, 2):", np.arange(2, 9, 2))
print("linspace(0, 10, 5):", np.linspace(0, 10, num=5))

zeros(2): [0. 0.]
ones(2): [1. 1.]
empty(2): [1. 1.]
arange(4): [0 1 2 3]
arange(2, 9, 2): [2 4 6 8]
linspace(0, 10, 5): [ 0.   2.5  5.   7.5 10. ]


In [53]:
# Cell 3: 정렬 및 배열 결합
arr = np.array([7, 3, 12, 1, 13, 5])
print("정렬 결과:", np.sort(arr))

a = np.array([1, 4, 5, 7])
b = np.array([3, 6, 12, 13])
print("배열 결합:", np.concatenate((a, b)))

x = np.array([[1, 7], [4, 5]])
y = np.array([[12, 13]])
print("2차원 결합(축 0):\n", np.concatenate((x, y), axis=0))

정렬 결과: [ 1  3  5  7 12 13]
배열 결합: [ 1  4  5  7  3  6 12 13]
2차원 결합(축 0):
 [[ 1  7]
 [ 4  5]
 [12 13]]


In [54]:
# Cell 4: 배열의 속성 확인 (3차원 배열)
array_example = np.array([[[3, 12], [1, 6]],
                          [[3, 12], [1, 6]],
                          [[3, 12], [1, 6]]])

print("차원 수(ndim):", array_example.ndim)        # 3
print("전체 요소 개수(size):", array_example.size)  # 12 (3*2*2)
print("배열 형태(shape):", array_example.shape)     # (3, 2, 2)

차원 수(ndim): 3
전체 요소 개수(size): 12
배열 형태(shape): (3, 2, 2)


In [55]:
# Cell 5: 배열 형태 변경 (Reshape)
a = np.arange(12)
print("원본 a:", a)

b = a.reshape(3, 4)
print("reshape(3, 4) 결과:\n", b)

print("reshape(2, 6) 결과:\n", np.reshape(a, shape=(2, 6), order='C'))

원본 a: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshape(3, 4) 결과:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
reshape(2, 6) 결과:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [56]:
# Cell 6: 새로운 축 추가 (newaxis, expand_dims)
a = np.array([1, 4, 5, 7, 12, 13])
print("원본 형태:", a.shape)

row_vector = a[np.newaxis, :]
col_vector = a[:, np.newaxis]
print("행 벡터 형태:", row_vector.shape)   # (1, 6)
print("열 벡터 형태:", col_vector.shape)   # (6, 1)

b = np.expand_dims(a, axis=1)
c = np.expand_dims(a, axis=0)
print("인덱스 1에 축 추가:", b.shape)
print("인덱스 0에 축 추가:", c.shape)

원본 형태: (6,)
행 벡터 형태: (1, 6)
열 벡터 형태: (6, 1)
인덱스 1에 축 추가: (6, 1)
인덱스 0에 축 추가: (1, 6)


In [57]:
# Cell 7: 인덱싱, 슬라이싱 및 조건부 선택
data = np.array([1, 4, 7])
print("슬라이싱 data[0:2]:", data[0:2])

a = np.array([[1, 4, 5, 7], [3, 6, 12, 13], [14, 15, 16, 17]])
print("5보다 작은 요소:", a[a < 5])

divisible_by_2 = a[a % 2 == 0]
print("짝수 요소들:", divisible_by_2)

슬라이싱 data[0:2]: [1 4]
5보다 작은 요소: [1 4 3]
짝수 요소들: [ 4  6 12 14 16]


In [58]:
# Cell 8: np.nonzero()를 이용한 인덱스 추출
a = np.array([[1, 4, 5, 7], [3, 6, 12, 13], [14, 15, 16, 17]])

b = np.nonzero(a < 5)
print("5보다 작은 요소의 인덱스:", b)
print("찾은 요소들:", a[b])

5보다 작은 요소의 인덱스: (array([0, 0, 1]), array([0, 1, 0]))
찾은 요소들: [1 4 3]


In [59]:
# Cell 9: 수직/수평 쌓기 및 나누기
a1 = np.array([[1], [7]])
a2 = np.array([[4], [5]])

print("vstack:\n", np.vstack((a1, a2)))
print("hstack:\n", np.hstack((a1, a2)))

x = np.arange(1, 25).reshape(2, 12)
print("3등분 결과:\n", np.hsplit(x, 3))

vstack:
 [[1]
 [7]
 [4]
 [5]]
hstack:
 [[1 4]
 [7 5]]
3등분 결과:
 [array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]


In [60]:
# Cell 10: 뷰(View)와 복사(Copy)
a = np.array([[1, 4, 5, 7], [3, 6, 12, 13], [14, 15, 16, 17]])

# View: 얕은 복사 -> 원본도 함께 바뀜
b1 = a[0, :]
b1[0] = 99
print("View 수정 후 원본 a:\n", a)   # 0행 0열이 99로 변경됨

# Copy: 깊은 복사 -> 원본은 그대로
b2 = a.copy()
b2[0, 0] = 1
print("Copy 수정 후 원본 a:\n", a)   # 99 유지

View 수정 후 원본 a:
 [[99  4  5  7]
 [ 3  6 12 13]
 [14 15 16 17]]
Copy 수정 후 원본 a:
 [[99  4  5  7]
 [ 3  6 12 13]
 [14 15 16 17]]


In [61]:
# Cell 11: 기본 배열 연산 및 브로드캐스팅
data = np.array([1, 7])
ones = np.ones(2, dtype=int)

print("더하기:", data + ones)
print("곱하기:", data * data)

print("스칼라 곱(data * 1.6):", data * 1.6)

더하기: [2 8]
곱하기: [ 1 49]
스칼라 곱(data * 1.6): [ 1.6 11.2]


In [62]:
# Cell 11: 기본 배열 연산 및 브로드캐스팅
data = np.array([1, 7])
ones = np.ones(2, dtype=int)

print("더하기:", data + ones)
print("곱하기:", data * data)

print("스칼라 곱(data * 1.6):", data * 1.6)

더하기: [2 8]
곱하기: [ 1 49]
스칼라 곱(data * 1.6): [ 1.6 11.2]


In [63]:
# Cell 13: 난수 생성 및 고유값 확인
rng = np.random.default_rng()
print("랜덤 정수 배열(2x4):\n", rng.integers(5, size=(2, 4)))

a = np.array([11, 11, 14, 17, 23, 38, 14, 23])
unique_values, counts = np.unique(a, return_counts=True)
print("고유값:", unique_values)
print("빈도수:", counts)

랜덤 정수 배열(2x4):
 [[3 1 3 1]
 [2 4 2 0]]
고유값: [11 14 17 23 38]
빈도수: [2 2 1 2 1]


In [64]:
# Cell 14: 배열 뒤집기 (Flip)
arr_2d = np.array([[1, 4, 5, 7], [3, 6, 12, 13], [14, 15, 16, 17]])

print("전체 뒤집기:\n", np.flip(arr_2d))
print("행 뒤집기:\n", np.flip(arr_2d, axis=0))

전체 뒤집기:
 [[17 16 15 14]
 [13 12  6  3]
 [ 7  5  4  1]]
행 뒤집기:
 [[14 15 16 17]
 [ 3  6 12 13]
 [ 1  4  5  7]]
